src/app/mod_msg/controllers.py
import datetime

from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for, session, abort

from app.mod_auth.autorization_required import requires_sign_in, get_unread_messages_count

from app.model.user import User, Message
from app.model.offer import Offer

from app import db

mod_msg = Blueprint('msg', __name__, url_prefix='/message')


def is_logged_in_as_specific_user_id(expected_id):
    if 'username' not in session:
        return False
    username = session['username']
    actual_id = User.query.filter_by(email=username).first().id
    return actual_id == expected_id


@mod_msg.route('/', methods=['GET'])
@requires_sign_in()
def index():
    msgs = Message.query.filter_by(to_id=session['user_id'])
    return render_template('msg/index.html', messages=list(msgs))


@mod_msg.route('/<int:id>', methods=['GET'])
@requires_sign_in()
def show(id):
    msg = Message.query.get(id)
    if msg is None:
        abort(404)
    if not is_logged_in_as_specific_user_id(msg.to_id):
        abort(403)
    msg.is_read = True
    db.session.commit()

    session['unread_messages'] = get_unread_messages_count()

    return render_template('msg/details.html', message=msg)

@mod_msg.route('/delete/<int:id>', methods=['POST'])
@requires_sign_in()
def delete(id):
    msg = Message.query.get(id)
    if msg is None:
        abort(404)
    if not is_logged_in_as_specific_user_id(msg.to_id):
        abort(403)
    db.session.delete(msg)
    db.session.commit()
    flash('Usunięto wiadomość')
    return redirect(url_for('msg.index'))

@mod_msg.route('/want_buy/<int:offer_id>', methods=['POST'])
@requires_sign_in()
def want_buy(offer_id):
    offer = Offer.query.get(offer_id)
    if offer is None:
        abort(404)
    if is_logged_in_as_specific_user_id(offer.owner_id):
        flash("Nie możesz kupić własnego mieszkania!")
        abort(403)
    msg = Message()
    msg.from_id = session['user_id']
    msg.is_read = False
    msg.sent_datetime = datetime.datetime.now()
    msg.to_id = offer.owner_id
    msg.offer_id = offer_id

    db.session.add(msg)
    db.session.commit()

    flash("Zgłoszono chęć zakupu")
    return redirect(url_for('offer.show_offer', offer_id=offer.id))\

src/app/mod_offer/controller.py
import datetime

from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for, abort

from app.mod_msg.controllers import is_logged_in_as_specific_user_id
from app.mod_offer.forms import CreateOfferForm

from app import db

from app.model import offer
from app.model.offer import Offer, Photo
from app.model.user import User, Message
from app.mod_auth.autorization_required import requires_sign_in
from app.model.validator import ValidationError, CombinedValidator, OfferValidator

import uuid
import os

mod_offer = Blueprint('offer', __name__, url_prefix='/offer')


def logged_user():
    if 'username' in session:
        return User.query.filter_by(email=session['username']).first()
    else:
        return None


@mod_offer.route('/', methods=['GET'])
def index():
    query = Offer.query.filter(Offer.is_sold == False).order_by(Offer.publish_date.desc())

    offers = query.all()
    return render_template('offer/index.html', offers=offers)


@mod_offer.route('/', methods=['POST'])
def create():
    offer = Offer()
    offer.city = request.form['city']
    offer.street = request.form['street']
    offer.building_number = request.form['building_number']
    try:
        offer.apartment_number = int(request.form['apartment_number'])
    except:
        offer.apartment_nuber = None
    offer.room_count = int(request.form['room_count'])
    offer.area = int(request.form['area'])
    offer.tier = int(request.form['tier'])
    offer.has_balcony = 'has_balcony' in request.form and request.form['has_balcony'] == 'on'
    offer.description = request.form['description']
    offer.price = int(request.form['price'])
    offer.owner_id = session['user_id']
    offer.publish_date = datetime.datetime.now()
    offer.is_sold = False

    validator = OfferValidator(lambda: offer)

    errors, valid = validator.validate()
    if not valid:
        for e in errors:
            flash(e.message)
        return redirect(url_for('offer.create_form'))

    db.session.add(offer)
    db.session.commit()

    for fname in request.files:
        file = request.files[fname]
        if file.filename == '':
            continue

        _, ext = os.path.splitext(file.filename)
        storename = uuid.uuid4().hex + ext
        file.save('/home/ec2-user/kwadrat/src/app/static/' + storename)

        photo = Photo()
        photo.offer_id = offer.id
        photo.filename = storename

        db.session.add(photo)

    db.session.commit()

    flash("Dodano ogłoszenie", "alert-success")

    return redirect(url_for("offer.show_offer", offer_id=offer.id))


@mod_offer.route('/create/', methods=['GET'])
@requires_sign_in()
def create_form():
    return render_template('offer/create.html')


def handle_recent(offer):
    recent_ones = session['recent'] if 'recent' in session else []
    for d in recent_ones:
        if d['offer_id'] == offer.id:
            return
    current_one = {
        'offer_id': offer.id,
        'city': offer.city,
        'street': offer.street,
        'price': offer.price,
    }
    if len(recent_ones) >= 3:
        recent_ones = recent_ones[1:]
    recent_ones = [current_one] + recent_ones
    session['recent'] = recent_ones


@mod_offer.route('/<int:offer_id>', methods=['GET'])
def show_offer(offer_id=None):

    offer = Offer.query.get(offer_id)
    if offer is None:
        abort(404)
    handle_recent(offer)

    already_requested = 'user_id' in session and Message.query.filter_by(from_id=session['user_id'], offer_id=offer.id).first() is not None

    return render_template('offer/show.html', offer=offer, already_requested=already_requested)


def CreateFilter(param_name, param_desc, param_func, column):
    return GenericFilter(param_func, param_name, param_desc, column)

def CreateIntFilter(param_name, param_desc, param_func, column):
    return IntFilter(param_func, param_name, param_desc, column)

def CreateBoolFilter(param_name, param_desc, param_func, column):
    return BoolFilter(param_func, param_name, param_desc, column)


class GenericFilter(object):
    def __init__(self, params, param_name, param_desc, column):
        self.param_desc = param_desc
        self.param_name = param_name
        self.column = column
        self.param_func = params

    def validate(self):
        params = self.param_func()
        self.enabled = params.get(self.param_name + '_enabled', 'off') == 'on'
        lower = params.get(self.param_name + '_lower', '')
        upper = params.get(self.param_name + '_upper', '')

        if not self.enabled:
            return [], True

        if lower.isdigit() and upper.isdigit():
            if int(lower) <= int(upper):
                self.lower_val = int(lower)
                self.upper_val = int(upper)
                return [], True

        return [ValidationError('Niepoprawny przedział: ' + self.param_desc)], False

    def filter(self, query):
        if self.enabled and self.validate()[1]:
            return query.filter(self.column.between(self.lower_val, self.upper_val))
        return query



class IntFilter(object):
    def __init__(self, params, param_name, param_desc, column):
        self.param_desc = param_desc
        self.param_name = param_name
        self.column = column
        self.param_func = params

    def validate(self):
        params = self.param_func()
        self.enabled = params.get(self.param_name + '_enabled', 'off') == 'on'
        arg = params.get(self.param_name, '')

        if not self.enabled:
            return [], True

        if arg.isdigit():
            self.value = int(arg)
            return [], True

        return [ValidationError('Niepoprawna wartosć: ' + self.param_desc)], False

    def filter(self, query):
        if self.enabled and self.validate()[1]:
            return query.filter(self.column == self.value)
        return query

class BoolFilter(object):
    def __init__(self, params, param_name, param_desc, column):
        self.param_desc = param_desc
        self.param_name = param_name
        self.column = column
        self.param_func = params

    def validate(self):
        params = self.param_func()
        self.enabled = params.get(self.param_name + '_enabled', 'off') == 'on'
        arg = params.get(self.param_name, '')

        if not self.enabled:
            return [], True

        self.value = arg == 'on'

        return [], True

    def filter(self, query):
        if self.enabled and self.validate()[1]:
            return query.filter(self.column == self.value)
        return query

# class RoomFilter(object):
#     def __init__(self, params):
#         self.param_func = params
#
#     def validate(self):
#         params = self.param_func()
#         self.enabled = params.get('room_count_enabled', 'off') == 'on'
#         lower = params.get('room_count_lower', '')
#         upper = params.get('room_count_upper', '')
#
#         if not self.enabled:
#             return [], True
#
#         if lower.isdigit() and upper.isdigit():
#             if int(lower) <= int(upper):
#                 self.lower_val = int(lower)
#                 self.upper_val = int(upper)
#                 return [], True
#
#         return [ValidationError('Niepoprawny przedział: liczba pokoi')], False
#
#     def filter(self, query):
#         if self.enabled:
#             return query.filter(Offer.room_count.between(self.lower_val, self.upper_val))
#         return query

@mod_offer.route('/my/',methods=['GET'])
@requires_sign_in()
def my_offers():
    offers = Offer.query.filter_by(owner_id=session['user_id']).all()
    return render_template('offer/my.html', offers=offers)

@mod_offer.route('/delete/<int:offer_id>', methods=['POST'])
def delete(offer_id):
    offer = Offer.query.get(offer_id)
    if offer.owner_id != session['user_id']:
        return 403

    for p in offer.photos:
        db.session.delete(p)
    Message.query.filter_by(offer_id=offer.id).delete()
    db.session.delete(offer)
    db.session.commit()
    flash("Usunięto ofertę")
    return redirect(url_for('offer.my_offers'))

@mod_offer.route('/edit/<int:offer_id>', methods=['GET'])
@requires_sign_in()
def edit(offer_id):
    offer = Offer.query.get(offer_id)
    if offer.owner_id != session['user_id']:
        return 403
    return render_template('offer/edit.html', offer=offer)

@mod_offer.route('/edit/<int:offer_id>', methods=['POST'])
@requires_sign_in()
def edit_post(offer_id):
    offer = Offer.query.get(offer_id)
    if offer.owner_id != session['user_id']:
        return 403
    offer.city = request.form['city']
    offer.street = request.form['street']
    offer.building_number = request.form['building_number']
    offer.apartment_number = int(request.form['apartment_number'])
    offer.room_count = int(request.form['room_count'])
    offer.area = int(request.form['area'])
    offer.tier = int(request.form['tier'])
    offer.has_balcony = 'has_balcony' in request.form and request.form['has_balcony'] == 'on'
    offer.description = request.form['description']
    offer.price = int(request.form['price'])
    offer.owner_id = session['user_id']
    offer.publish_date = datetime.datetime.now()
    offer.is_sold = False

    validator = OfferValidator(lambda: offer)

    errors, valid = validator.validate()
    if not valid:
        for e in errors:
            flash(e.message)
        return redirect(url_for('offer.edit', offer_id=offer.id))

    db.session.commit()
    flash("Zaktualizowano ogłoszenie")

    return redirect(url_for("offer.show_offer", offer_id=offer.id))


@mod_offer.route('/search/', methods=['GET'])
def search():
    params = request.args.to_dict()

    query = Offer.query

    filters = [
        CreateFilter('room_count', 'liczba pokoi', lambda: params, Offer.room_count),
        CreateFilter('area', 'powierzchnia', lambda: params, Offer.area),
        CreateFilter('price', 'cena', lambda: params, Offer.price),
        CreateIntFilter('tier', 'piętro', lambda: params, Offer.tier),

src/app/templates/offer/create.html
{% extends 'layout.html' %}
{% block body %}
    <form method="post" action="{{ url_for('offer.index') }}"
          enctype=multipart/form-data >

        <div class="form-group">
            <div>
                <label class=col-sm-2 control-labelfor="city"
                       class="col-sm-2 control-label">Miasto</label>

                    <div class="col-sm-10"><input class="form-control"
                                                  class="form-control" id="city"
                                                  name="city" type="text"
                                                  required minlength="1"
                                                  maxlength="64" title="Miasto">
                    </div>


                <div>
                    <label class=col-sm-2
                           control-labelfor="street">Ulica</label>
                    <div class="col-sm-10"><input class="form-control"
                                                  id="street" name="street"
                                                  type="text" required
                                                  minlength="1" maxlength="128"
                                                  title="Ulica">
                    </div>
                </div>
                <div>
                    <label class=col-sm-2 control-labelfor="building_number">Nr
                        domu</label>
                    <div class="col-sm-10"><input class="form-control"
                                                  id="building_number"
                                                  name="building_number"
                                                  type="text" required
                                                  pattern="\d+[a-zA-Z]?"
                                                  title="Nr domu (np. 17 lub 35c)">
                    </div>
                </div>
                <div>
                    <label class=col-sm-2 control-labelfor="apartment_number">Nr
                        mieszkania</label>
                    <div class="col-sm-10"><input class="form-control"
                                                  id="apartment_number"
                                                  name="apartment_number"
                                                  type="number" min="1"
                                                  title="Nr mieszkania np. 4">
                    </div>
                </div>
                <div>
                    <label class=col-sm-2 control-labelfor="room_count">Liczba
                        pokoi</label>
                    <div class="col-sm-10"><input class="form-control"
                                                  id="room_count"
                                                  name="room_count"
                                                  type="number" required min="1"
                                                  step="1"
                                                  title="Ilość pokoi np. 3">
                    </div>
                </div>
                <div>
                    <label class=col-sm-2 control-labelfor="area">Powierzchnia m<sup>2</sup></label>
                    <div class="col-sm-10"><input class="form-control" id="area"
                                                  name="area" type="number"
                                                  required min="1" step="1"
                                                  title="Wielkość w metrach kwadratowych">
                    </div>
                </div>
                <div>
                    <label class=col-sm-2 control-labelfor="tier">Piętro (0
                        jeśli parter)</label>
                    <div class="col-sm-10"><input class="form-control" id="tier"
                                                  name="tier" type="number"
                                                  required min="0" step="1"
                                                  title="Piętro (dla parteru prosze wpisać 0)">
                    </div>
                </div>
                <div>
                    <label class=col-sm-2
                           control-labelfor="has_balcony">Balkon</label>
                    <input class="form-control"
                                                  id="has_balcony"
                                                  name="has_balcony"
                                                  type="checkbox"
                                                  title="Balkon">

                </div>
                <div>
                    <label class=col-sm-2
                           control-labelfor="description">Opis</label>
                    <div class="col-sm-10"><textarea class="form-control"
                                                  id="description"
                                                  name="description" type="text"
                                                  required minlength="1"
                                                  maxlength="6144" title="Opis">
                        </textarea>
                    </div>
                </div>
                <div>
                    <label class=col-sm-2 control-labelfor="price">Cena (Złote
                        Polskie)</label>
                    <div class="col-sm-10"><input class="form-control"
                                                  id="price" name="price"
                                                  type="number" required min="1"
                                                  step="1"
                                                  title="Cena w pelnych złotych">
                    </div>
                </div>
                <div>
                    <label class=col-sm-2 control-labelfor="photos">Zdjęcie
                        1</label>
                    <div class="col-sm-10"><input class="form-control"
                                                  id="photo1" name="photo1"
                                                  type="file" title="Zdjęcie 1" required >
                    </div>
                </div>
                <div>
                    <label class=col-sm-2 control-labelfor="photo2">Zdjęcie
                        2</label>
                    <div class="col-sm-10"><input class="form-control"
                                                  id="photo2" name="photo2"
                                                  type="file" title="Zdjęcie2">
                    </div>
                </div>
                <div>
                    <label class=col-sm-2 control-labelfor="photo3">Zdjęcie
                        3</label>
                    <div class="col-sm-10"><input class="form-control"
                                                  id="photo3" name="photo3"
                                                  type="file" title="Zdjęcie3">
                    </div>
                </div>
                <div>
                    <label class=col-sm-2 control-labelfor="photo4">Zdjęcie
                        4</label>
                    <div class="col-sm-10"><input class="form-control"
                                                  id="photo4" name="photo4"
                                                  type="file" title="Zdjęcie4">
                    </div>
                </div>
                <div>
                    <label class=col-sm-2 control-labelfor="photo5">Zdjęcie
                        5</label>
                    <div class="col-sm-10"><input class="form-control"
                                                  id="photo5" name="photo5"
                                                  type="file" title="Zdjęcie5">
                    </div>
                </div>
            </div>
        </div>
        <button type="submit">Wystaw ogłoszenie</button>

    </form>
{% endblock %}

src/app/templates/offer/edit.html
{% extends 'layout.html' %}
{% block body %}
    <form method="post" action="{{ url_for('offer.edit_post', offer_id=offer.id)}}" enctype=multipart/form-data>
        <fieldset>
            <ul>
                <li>
                    <label for="city">Miasto</label>
                    <input id="city" name="city" type="text" required minlength="1" maxlength="64" title="Miasto" value="{{ offer.city }}">
                </li>
                <li>
                    <label for="street">Ulica</label>
                    <input id="street" name="street" type="text" required minlength="1" maxlength="128" title="Ulica" value="{{ offer.street }}">
                </li>
                <li>
                    <label for="building_number">Nr domu</label>
                    <input id="building_number" name="building_number" type="text" required pattern="\d+[a-zA-Z]?" title="Nr domu (np. 17 lub 35c)" value="{{ offer.building_number }}">
                </li>
                <li>
                    <label for="apartment_number">Nr mieszkania</label>
                    <input id="apartment_number" name="apartment_number" type="number" min="1" title="Nr mieszkania np. 4" value="{{ offer.apartment_number }}">
                </li>
                <li>
                    <label for="room_count">Liczba pokoi</label>
                    <input id="room_count" name="room_count" type="number" required min="1" step="1" title="Ilość pokoi np. 3" value="{{ offer.room_count }}">
                </li>
                <li>
                    <label for="area">Powierzchnia m<sup>2</sup></label>
                    <input id="area" name="area" type="number" required min="1" step="1" title="Wielkość w metrach kwadratowych" value="{{ offer.area }}">
                </li>
                <li>
                    <label for="tier">Piętro (0 jeśli parter)</label>
                    <input id="tier" name="tier" type="number" required min="0" step="1" title="Piętro (dla parteru prosze wpisać 0)" value="{{ offer.tier }}">
                </li>
                <li>
                    <label for="has_balcony">Balkon</label>
                    <input id="has_balcony" name="has_balcony" type="checkbox" title="Balkon" {{ 'checked="on' if offer.has_balcony }} >
                </li>
                <li>
                    <label for="description">Opis</label>
                    <input id="description" name="description" type="text" required minlength="1" maxlength="6144" title="Opis" value="{{ offer.description }}">
                </li>
                <li>
                    <label for="price">Cena (Złote Polskie)</label>
                    <input id="price" name="price" type="number" required min="1" step="1" title="Cena w pelnych złotych" value="{{ offer.price }}">
                </li>
            </ul>
            <button type="submit">Zapisz zmiany</button>
        </fieldset>
    </form>
{% endblock %}

src/app/templates/offer/index.html
{% extends 'layout.html' %}
{% block body %}
    <table>
        <tbody>
        {% for offer in offers %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ offer.city }}</td>
                <td>{{ offer.street }}</td>
                <td>{{ offer.building_number }}</td>
                <td>{{ offer.apartment_number }}</td>
                <td>{{ offer.room_count }}</td>
                <td>{{ offer.area }}</td>
                <td>{{ offer.tier }}</td>
                <td>{{ offer.has_balcony }}</td>
                <td>{{ offer.price }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/app/templates/offer/my.html
{% extends 'layout.html' %}
{% block body %}
    {% if offers | length > 0 %}
    <table class="table table-striped table-condensed table-hover">
        <tbody>
        {% for offer in offers %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ offer.city }}</td>
                <td>{{ offer.street }} {{ offer.building_number }}
                    {% if offer.apartment_number %}
                    m. {{ offer.apartment_number }}
                {% endif %}
                <td>{{ offer.room_count }} pokoje</td>
                <td>{{ offer.area }} m<sup>2</sup></td>
            {% if offer.tier == 0 %}
                <td>parter</td>
            {% else %}
                <td>{{ offer.tier }} piętro</td>
            {% endif %}
                <td>{{ "Balkon" if offer.has_balcony}}</td>
                <td>{{ '{0:,}'.format(offer.price).replace(',', ' ') }} zł</td>
                <td><a href="{{ url_for('offer.show_offer', offer_id=offer.id) }}">Szczegóły</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h1>Nie masz żadnych wystawionych ofert</h1>
    {% endif %}
{% endblock %}

src/app/templates/offer/show.html
{% extends 'layout.html' %}
{% block body %}
    <div>
    <a href="{{ url_for('offer.search') }}">Powrót do wyszukiwania</a>
        {% if session['user_id'] == offer.owner_id %}
            <p class="alert alert-info" >To jest Twoja oferta</p>
            {% if  offer.is_sold %}
                <p>Nieruchomość została już sprzedana</p>
            {% else %}
                <form action="{{ url_for('offer.sold', offer_id=offer.id) }}" method="post">
                    <button type="submit" class="btn btn-danger">Oznacz jako sprzedane</button>
                </form>
            {% endif %}



    {% else %}
            {% if already_requested %}
                <p>Już zgłosiłeś chęć zakupu tej nieruchomości</p>
            {% else %}
                <form action="{{ url_for('msg.want_buy', offer_id=offer.id) }}" method="post">
                    <button type="submit" class="btn btn-success">Chcę kupić!</button>
                </form>
            {% endif %}
        {% endif %}

        <h1>Szczegóły oferty:</h1>

        <dl class="dl-horizontal">
        <dt>Miasto:    </dt><dd>{{ offer.city }}</dd>
        <dt>Ulica:    </dt><dd>{{ offer.street }}</dd>
        <dt>Nr budynku: </dt><dd>{{ offer.building_number }}</dd>
        <dt>Nr mieszkania: </dt><dd>{{ offer.apartment_number }}</dd>
        <dt>Liczba pokoi: </dt><dd>{{ offer.room_count }}</dd>
        <dt>Powierzchnia: </dt><dd> {{offer.area }} m<sup>2</sup></dd>
        <dt>Kodnygnacje:</dt><dd> {{ offer.tier }}</dd>
        <dt>Posiada balkon: </dt><dd>{{ "TAK" if offer.has_balcony else "NIE"}}</dd>
        <dt>Cena: </dt><dd> {{ offer.price }}zł</dd>
        <dt>Opis: </dt><dd>{{ offer.description }}</dd>
                                  </dl>
        <div>
            <h2>Zdjęcia</h2>


        {% for photo in offer.photos %}
            <img class="img-responsive" src="/static/{{ photo.filename }}">
        {% endfor %}
        <br>
        </div>

    </div>

{% if offer.owner_id == session['user_id'] %}
                <form action="{{ url_for('offer.delete', offer_id=offer.id) }}" method="post">
                    <button class="btn btn-danger" type="submit">Usuń</button>
                </form>

                    <a class="btn" href="{{ url_for('offer.edit', offer_id=offer.id) }}">Edytuj</a>
{% endif %}

</div>
{% endblock %}